id: P36C9BBD9
initial_creation_type: input
source_metadata:
  title: Dudjom Rinpoche Series
  language: pt
  description: 'We present the following texts by Kyabje Dudjom Rinpoche Jikdral Yeshe
    Dorje (bdud ''joms ''jigs bral ye shes rdo rje, 1904–1987), the renowned yogi
    and scholar and first appointed head of the Nyingma school in exile:'
  volume:
    58366171c2ec4df08cd7fbfacaaad82e:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Advice
    d8f549c7905b41be8607fbe3e1833d4d:
      title: The Concise Benefits of the Festival of the Tenth Day
      parent: Benefits
    cf0aff374f284cb8a476ae38e31a5684:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    73263b92061942e18f64f77ab72f7b1e:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    4fd368d54aac4671ac4945422dc88a42:
      title: Concise Consecration
      parent: Consecration
    bc824a487f904d3ba3d948a867f175b6:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Dharma Protectors
    a8b37d99b0724ad49eaf2ab479a277f9:
      title: Dzogchen Aspiration Prayer
      parent: Dzogchen
    9448520724894638b626c087b2880c98:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Dzogchen
    6d855836bc8f4892946d3b0fc6fbb31e:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Dzogchen
    773f660b38a0463580b154411774c92e:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Guru Rinpoche Prayers
    14595bb52f9641839d1ce5ff17d75bf7:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Guru Rinpoche Prayers
    31cb4283bad949f38ce777d216ce5343:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Guru Rinpoche Prayers
    bb1039b97ecd4412978c98f3c924665c:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Guru Rinpoche Prayers
    fdd49ad501fb4678be3918b076531dea:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Guru Rinpoche Prayers
    dadb30b53bf34e17808311ab9ae64960:
      title: A Concise Lineage Prayer
      parent: Lineage Prayers
    384787f0333b44938fde6791093de02c:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    b0a3fcccf17e41deb6f62de193dbdcbc:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    9147204e092b473893ada26514317e95:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    d88c4ade99154600bd6ffaf3942874cf:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    b2976b8a47cc4fc980ea227fc67a7b0b:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Long Life Prayers
    8fe53204c23e43a9871a1f3157f7d41c:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Ngöndro
    f72d7fa90888442d8d7d6bfa28ef0e0e:
      title: Brief Notes on the Visualization for the Concise Recitation of the Pure
        Vision Preliminary Practice
      parent: Ngöndro
    287f17969bdd49618c70b11f4e5786f7:
      title: Brief Red Sur Offering
      parent: Offering
    67515b293cca442b8c60204628322d17:
      title: Brief Sur Offering
      parent: Offering
    9a36202fea13422398f2bf7af183ef7b:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayers
    7fe9a94df0fe45389ae17f69d8ff01e1:
      title: Essence and Embodiment of All the Buddhas
      parent: Prayers
    34c6bda78a734d3485dbb29f94b39a37:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    6a3916498d9f4381aaaa5d1460ad8c63:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Sādhanas
    3adb990a8a94498aba4860fcc2de8ded:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    ed3fb3f7fc0e417a8063fa83ee8f1357:
      title: A Daily Practice of Lama Sangdü
      parent: Sādhanas
    0dd93800c8154864857ed0305d9d87a3:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    048f2521652c4ec8a9e0cd494d9bdc80:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Sādhanas
    c940e4ea2a5e4fdbab15370263c7b07b:
      title: Daily Practice of Dorje Gotrab
      parent: Sādhanas
    a275c4b9c60843cba8e4ab94b0f5db27:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sādhanas
    45f43ca550a847c796dcc24e71f1ffff:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
    6f55ca5d0afc4b749357445714084e0d:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Sādhanas
    78aacc8e3ffa47f098a72ab9003095f4:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    98f1cde380a34236a5bacc39e2f3a373:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    0fbf4c2787be4fe2936ad36b21fb56bb:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Sang Offering
    a7eb363b70474173a21aa6a940fa75b2:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
    373eede5ed37490387cbd8d7c6c5ed05:
      title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying
        (Sojong) the Three Sets of Vows'
      parent: Sojong
    26d7b817d5e64303a811d2711c8a7919:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Tsok
    3257fa82f38442c9a46ab6ad16497868:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Tsok
    edcbe848d0e14540bbbad6256b32255d:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-02-28T23:10:30.055259'
last_modified_at: '2022-02-28T23:10:30.055263'
